name: Unit Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '12.18.x'
          
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Install Dependecies
        run: npm install

      - name: Run tests
        run: npm run test
